
language: node_js
node_js:
  - 10
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
deploy:
  - provider: script
    script: deploy-prod.sh
    on:
      branch: master
  - provider: script
    script: deploy-dev.sh
    on:
      branch: feature/ci
