
language: node_js
node_js:
  - 10
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: feature/ci
